### ISSUE TITLE
Using the built-in js/Promise when available

### ISSUE THREAD

**Issue by grav** [funcool/promesa#11]
How come Promesa is always using bluebird.js? Why not use the built-in Promises in eg Chrome and Safari? Do they have different semantics?

**Comment by niwinz** [comment]
No, they behave in the same way. The problem with native es6 promises are:
- They are very limited: they does not offers methods for sync inspection.
- They are bad for development: its stracktraces are very limited in comparison to bluebird.
- They are very slow: bluebird at this moment is the fastest promise impl https://github.com/petkaantonov/bluebird/tree/master/benchmark
- They does not support cancellation.

Using es6 promise I think is not an option because of its very limited api and bad performance.

**Comment by grav** [comment]
Thanks for the clarification! :-)
