### ISSUE TITLE
prom/all throwing exceptions

### ISSUE THREAD

**Issue by AndreaCrotti** [funcool/promesa#110]
We encountered a weird issue today after an upgrade to the latest promesa version (we were on a very old 2.0.1).

Here is a namespace to reproduce the issue:

```clojure
(ns repro
  (:require
   [promesa.core :as prom])
  (:import
   (java.util.concurrent CompletableFuture)))

(def p1 (prom/promise "all good"))

(def p2 (prom/rejected (ex-info "Not good" {})))

@(prom/all
  [p1])
;; => ["all good"]

(def all-failing (prom/all [p2]))
;; => #'repro/all-failing

(type all-failing)
;; => java.util.concurrent.CompletableFuture

@all-failing ; => BOOOM!!!

(def c (CompletableFuture. ))
(.complete c (Exception. "exception"))

(.get c)

@c ;; this is fine
```

Is it normal that a prom/all would just throw the exception automatically?
It didn't use to do it, and it seems like a weird behaviour. I thought for a bit that it was the CompletableFuture itself but it's not really, only wrapping an exception in a CompletableFuture doesn't behave the same way.

**Comment by niwinz** [comment]
This is expected behavior. On your example you are completing the completable future. The rejected future is completed exceptionally: look at https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletableFuture.html#completeExceptionally(java.lang.Throwable)

Completing a future with exception treats the exception as value so, the future is completed successfully and the return value is an instance of an exception. A `rejected` method returns a completablefurure completed exceptionally, so if you deref it, it raises the exception as  expected.  On your example, try to use `.completeExceptionally` instead of `.complete`.

**Comment by AndreaCrotti** [comment]
Ah ok, well I just find it very weird that just dereffing a promise an exception is thrown, and this wasn't the behaviour in promesa 2.0.1.
But anyway all good thanks for confirming.

**Comment by niwinz** [comment]
It wasnt this behavior because probably it was broken. This is an expected behavior, in JVM if you call .get on failed future, or .get the completable future that is exceptionally completed, the exception is raised in the thread you call `.get`. In the JS worlds if you `then` the rejected promise` it will not execute the callback (it only can execute the callback if `catch` callback is attached.
