### ISSUE TITLE
How can I use a bluebird promise with promesa ?

### ISSUE THREAD

**Issue by hipitihop** [funcool/promesa#28]
I'm using the orientjs node library which also claims to use the bluebird promises. How can I use promesa with the bluebird promises returned by orientjs API e.g. `(.query db "select from OUser")` returns a bluebird promise afaik. I can certainly do `(.then .... )` but not `(p/then ....)`

https://github.com/orientechnologies/orientjs

**Comment by niwinz** [comment]
Seems like the the orientjs bundle that you are using in cljs includes its own version of bluebird promise, and this is because `p/then` does not works on it. This library uses protocols and having an other copy of the library makes that one just implement that protocols and other no.

I'm not pretty clear how really this can be fixed. I'm really open to provide a way to solve this situations and help people to use promesa with other bundles that uses its own bluebird copy.

An othe issue that you should consider, is that you are including bluebird probably 2 times and this obviously impact in your code size.

**Comment by hipitihop** [comment]
Thanks for the prompt and detailed response. At this stage of my project I'm not concerned about the minimal code size effect but you have a fair point. I didn't realise node can load multiple versions of a package, I'm still new to node. Since I'm defining my deps (including npm) in my lein project,  I wonder if I can use :exclusions against orientjs.
While I'm familiar with promise/A I'm not familiar with bluebird or promesa so I'm unsure what promesa adds (apart from proper cljs syntax) on top of bluebird to make this goal worthwhile. I'd hate to waste anyone's time.

**Comment by niwinz** [comment]
This should be fixed in the latest version.
