### ISSUE TITLE
Migrate Bluebird to CLJSJS?

### ISSUE THREAD

**Issue by martinklepsch** [funcool/promesa#29]
Just a thought, I'd be happy to do it for you I guess.

**Comment by niwinz** [comment]
Personally I prefer maintain my own version of bluebird.

All cljsjs packages are direct packages of the js libraries, this means that they are not compatible to run  in nodejs with cljs (because many pacakges uses UMD bundles that firstly checks if module.exports exists and if it exists associates it to it instead to global, that makes them imposible to access through the `js/` special namespace in cljs). 

The bluebird bundle in promesa is specially modified in order to properly work in nodejs builds and browser ;)

**Comment by martinklepsch** [comment]
That makes sense, thanks for the explanation 👍
