### ISSUE TITLE
Support for futures, executors?

### ISSUE THREAD

**Issue by kingpong** [funcool/promesa#57]
Hi Andrey. My team has an internal library for using completablefuture in Clojure, but we'd rather use an open source lib. Promesa provides A lot of what we need, but there are a couple of gaps:
* a macro that works like `(future ...)` but returns a CompletableFuture
* ability to specify the executor for callbacks, including using `thenApply` vs `thenApplyAsync`

Would you be willing to accept contributions to support these things?

**Comment by niwinz** [comment]
Yeah, that will be welcome :D

**Comment by niwinz** [comment]
I think that the second point is pretty usable right now, the `+executor+` var is defined as `^:redef` so you can create a helper that swaps the executor before performing the map/bind operation. Obviously having that helper directly in promesa is also welcome. Maybe we need convert the `+executor+` var into dynamic var...

**Comment by niwinz** [comment]
I will start working on it (at least partially), I will expose a general purpose api for executors for the 4.0.0 release

**Comment by kingpong** [comment]
That’s great, thanks Andrey. Unfortunately for me, my team is no longer using Clojure (which is why I haven’t already contributed the code).

**Comment by niwinz** [comment]
Almost all the executors and schedulers is landed in master. I still don't know how to model the api for provide custom executors on `map`, `bind`, and related functions.

Also I have plan to provide api for execute completions synchronously (inlined) instead of all the chain asynchrnously (this is usefull when you need some performance, and this is jvm only).

**Comment by niwinz** [comment]
Finished.
