### ISSUE TITLE
`deliver` and `fail`?

### ISSUE THREAD

**Issue by vspinu** [funcool/promesa#60]
Maybe I am missing something obvious, but wouldn't it make sense to have core-like `deliver` and `fail` functions which could be used on promise objects? 

So basically:

```cl

(let [p (promise)]
   ...
   (if something (deliver p :good) (fail p (Exception. ...)))
   ...
  p)
```

Thanks!

**Comment by niwinz** [comment]
Because the "deferred" is an anti pattern.  If you need do something like this, just do the following:
```
(p/promise (fn [deliver fail] (if something (deliver :good) (fail (Exception. ...)))))
```

This api makes it clear who is the responsible of calling the `deliver` and `fail` functions. With your example (`deferred` pattern, anyone with access to promise object can deliver values, so you can expose it too much. 

Additionally, the `promise` object represents a deferred value, but does not represents the "factory" of value, it is very strange in terms of abstractions that the same object performs the both roles. In javascript some time ago existed that pattern (also called `deferred`) that is now also an antipatern:

- https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern
- https://www.datchley.name/promise-patterns-anti-patterns/

Please give me a real example of code that really needs the "deferred" pattern and can't be easily solved with the current approach and i'll reconsider my current approach and try to imlement it for both platforms.

**Comment by vspinu** [comment]
Cool. Thanks for looking into it!

**Comment by niwinz** [comment]
already in 2.0.1

**Comment by vspinu** [comment]
Nice. Thanks a bunch for this!
